VideoUploader/config/routes.rb
VideoUploader::Application.routes.draw do

  devise_for :users

  resources :postings do
    resources :uploads
  end

  root :to => 'postings#index'

end

VideoUploader/app/models/posting.rb
class Posting < ActiveRecord::Base
  has_many :uploads, :dependent => :delete_all
  belongs_to :user
  attr_accessible :title
end

VideoUploader/app/models/upload.rb
class Upload < ActiveRecord::Base
  belongs_to :posting
  attr_accessible :description, :name, :file_name
  validates_presence_of :name, :description, message: "is required field and can't be blank!"
  mount_uploader :file_name,  FileUploader
end

VideoUploader/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
  has_many :postings
end

VideoUploader/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

VideoUploader/app/controllers/postings_controller.rb
class PostingsController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :find_posting, :only => [:show]
  # GET /postings
  # GET /postings.json
  def index
    @postings = Posting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @postings }
    end
  end

  # GET /postings/1
  # GET /postings/1.json
  def show

  end

  # GET /postings/new
  # GET /postings/new.json
  def new
    @posting = Posting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @posting }
    end
  end

  # GET /postings/1/edit
  def edit
    @posting = Posting.find(params[:id])
  end

  # POST /postings
  # POST /postings.json
  def create
    @posting = Posting.new(params[:posting])
    @posting.user = current_user
    respond_to do |format|
      if @posting.save
        format.html { redirect_to @posting, notice: 'Posting was successfully created.' }
        format.json { render json: @posting, status: :created, location: @posting }
      else
        format.html { render action: "new" }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /postings/1
  # PUT /postings/1.json
  def update
    @posting = Posting.find(params[:id])

    respond_to do |format|
      if @posting.update_attributes(params[:posting])
        format.html { redirect_to @posting, notice: 'Posting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postings/1
  # DELETE /postings/1.json
  def destroy
    @posting = Posting.find(params[:id])
    @posting.destroy

    respond_to do |format|
      format.html { redirect_to postings_url }
      format.json { head :no_content }
    end
  end

  private

  def find_posting
    @posting = Posting.find(params[:id])

  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The posting you were looking for could not be found."
    redirect_to postings_path
  end
end

VideoUploader/app/controllers/uploads_controller.rb
class UploadsController < ApplicationController

  before_filter :find_posting
  before_filter :find_upload, :only => [:show, :edit, :update, :destroy]


  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = @posting.uploads

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @uploads }
    end
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
    @upload = @posting.uploads.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @upload }
    end
  end

  # GET /uploads/new
  # GET /uploads/new.json
  def new
    @upload = @posting.uploads.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @upload }
    end
  end

  # GET /uploads/1/edit
  def edit
    @upload = Upload.find(params[:id])
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = @posting.uploads.build(params[:upload])

    respond_to do |format|
      if @upload.save
        format.html { redirect_to [@posting, @upload], notice: 'Upload was successfully created.' }
      else
        flash[:alert] = "Upload has not been created."
        format.html { render action: "new"}
      end

    end
  end

  # PUT /uploads/1
  # PUT /uploads/1.json
  def update
    @upload = @posting.uploads.find(params[:id])

    respond_to do |format|
      if @upload.update_attributes(params[:upload])
        format.html { redirect_to @upload, notice: 'Upload was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload = @posting.uploads.find(params[:id])
    @upload.destroy

    respond_to do |format|
      format.html { redirect_to posting_url, message: "Ho Ho" }
      format.json { head :no_content }
    end
  end

  private

  def find_posting
    @posting = Posting.find(params[:posting_id])

  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The posting you were looking for could not be found."
    redirect_to postings_path
  end

  def find_upload
    @upload = @posting.uploads.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    flash[:alert] = "The upload you were looking for could not be found."
    redirect_to posting_uploads_path
  end
end

VideoUploader/app/helpers/application_helper.rb
module ApplicationHelper
end

VideoUploader/app/helpers/postings_helper.rb
module PostingsHelper
end

VideoUploader/app/helpers/uploads_helper.rb
module UploadsHelper
end

VideoUploader/app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

VideoUploader/app/views/layouts/_navigation.html.erb
<%= link_to "VideoUploader", root_path, :class => 'brand' %>
<ul class="nav pull-right">
  <% if user_signed_in? %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      Signed in as <%= current_user.email %>
      <b class="caret"></b>
    </a>
    <ul class="dropdown-menu">
      <li>
      <%= link_to('Edit account', edit_user_registration_path) %>
      </li>
      <li>
      <%= link_to('Sign out', destroy_user_session_path, :method=>'delete') %>
      </li>
    </ul>
  <% else %>
    <li>
    <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
    <li class="divider-vertical" />
    <li>
    <%= link_to('Sign in', new_user_session_path)  %>
    </li>
  <% end %>
</ul>

VideoUploader/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "VideoUploader" %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>
  <header class="navbar navbar-fixed-top">
    <nav class="navbar-inner">
      <div class="container">
        <%= render 'layouts/navigation' %>
      </div>
    </nav>
  </header>
  <div id="main" role="main">
    <div class="container">
      <div class="content">
       <div class="row">
        <div class="span12">
          <div class="well">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
      </div>
      <footer>
      </footer>
    </div>
  </div> <!--! end of .container -->
</div> <!--! end of #main -->
</body>
</html>

VideoUploader/app/views/postings/_form.html.erb
<%= form_for(@posting, html: {class: "form-horizontal"}) do |f| %>
<% if @posting.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@posting.errors.count, "error") %> prohibited this posting from being saved:</h2>
  <ul>
    <% @posting.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<fieldset>
  <legend><%= @form_title %></legend>
  <div class="control-group">
    <%= f.label :title, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :title, class: "input-xlarge" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
</fieldset>
<% end %>

VideoUploader/app/views/postings/edit.html.erb
<% @form_title = "Edit Posting" %>

<%= render 'form' %>

<%= link_to 'Show', @posting %> |
<%= link_to 'Back', postings_path %>

VideoUploader/app/views/postings/index.html.erb
<h2>Postings</h2>

<table class="table table-striped">
  <tr>
    <th>Title</th>
    <th>User</th>
    <th># of Uploads</th>
  </tr>

<% @postings.each do |posting| %>
  <tr>
    <td><%= link_to posting do %>
          <%= posting.title %>
        <% end %>
    </td>
    <td><%= posting.user.email %></td>
    <td><%= posting.uploads.count %></td>
    <td><%= link_to edit_posting_path(posting) do %>
          <i class="icon-edit"></i>
        <% end %>
    </td>
    <td><%= link_to posting, method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="icon-remove"></i>
        <% end %>
    </td>
  </tr>
<% end %>
</table>

<%= link_to new_posting_path, class: "btn" do %>
  <i class="icon-plus"></i>
<% end %>

VideoUploader/app/views/postings/new.html.erb
<% @form_title = "New Posting" %>
<%= render 'form' %>

<%= link_to 'Back', postings_path %>

VideoUploader/app/views/postings/show.html.erb
<!-- <p id="notice"><%= notice %></p>   -->
    <h2><%= @posting.title %></h2>
      <p>Created by <%= @posting.user.email %></p>

    <strong>Uploads</strong>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>
            Name
          </th>
          <th>
            Description
          </th>
          <th>
            File Name
          </th>
        </tr>
      </thead>
      <tbody>
        <% @posting.uploads.each do |upload| %>
        <tr>
          <td>
            <%= link_to upload.name, [@posting, upload] %>
          </td>
          <td>
            <%= upload.description %>
          </td>
          <td>
            <%= upload.file_name %>
          </td>
          <td>
            <i class="icon-download"></i>
          </td>
          <td>
            <%= link_to [:edit, @posting, upload] do %>
            <i class="icon-edit"></i>
            <% end %>
          </td>
          <td>
            <%= link_to [@posting, upload], method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="icon-remove"></i>
            <% end %>
          </td>
        </tr>
        <% end %>
        <tr>
          <td>
            <%= link_to new_posting_upload_path(@posting) do %>
            <i class="icon-plus"></i>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>


    <%= link_to 'Edit', edit_posting_path(@posting), class: "btn btn-link" %> |
    <%= link_to 'Back', postings_path, class: "btn btn-link" %>

VideoUploader/app/views/uploads/_form.html.erb
<%= form_for ([@posting, @upload]), html: {class: "form-horizontal", multipart: true} do |f| %>
<% if @upload.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

  <ul>
    <% @upload.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<fieldset>
  <legend><%= @form_title %></legend>
  <div class="control-group">
    <%= f.label :name, class: "control-label" %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
    <%= f.label :description, class: "control-label" %>
    <div class="controls">
      <%= f.text_area :description, rows: "3" %>
    </div>
    <%= f.label :file_name, class: "control-label" %>
    <div class="controls">
      <%= f.file_field :file_name, class: "input-xlarge" %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
</fieldset>

<% end %>

VideoUploader/app/views/uploads/edit.html.erb
<% @form_title = "Edit Upload" %>

<%= render 'form' %>

<%= link_to 'Show', [@posting, @upload] %> |
<%= link_to 'Back', posting_path %>
<%= link_to 'Delete Upload', [@posting, @upload], method: :delete, data: { confirm: 'Are you sure?' } %>

VideoUploader/app/views/uploads/index.html.erb
<h2>Uploads</h2>

<table class="table table-striped">
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th></th>
    <th></th>
  </tr>

<% @posting.uploads.each do |upload| %>
  <tr>
    <td><%= link_to upload.name, [@posting, upload] %></td>
    <td><%= upload.description %></td>
    <td><%= link_to 'Edit', [:edit, @posting, upload] %></td>
    <td><%= link_to 'Delete Upload', [@posting, upload], method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Upload', new_posting_upload_path %>

VideoUploader/app/views/uploads/new.html.erb
<% @form_title = "New Upload" %>

<%= render 'form' %>

<%= link_to 'Back', posting_uploads_path %>

VideoUploader/app/views/uploads/show.html.erb
<!-- <p id="notice"><%= notice %></p>   -->

<dl>
  <dt>Name</dt>
  <dd><%= @upload.name %></dd>
  <dt>Description</dt>
  <dd><%= @upload.description %></dd>
</dl>


<%= link_to 'Edit', edit_posting_upload_path(@upload) %> |
<%= link_to 'Back', posting_path(@posting) %>
<%= link_to 'Delete Upload', [@posting,@upload], method: :delete, data: { confirm: 'Are you sure?' } %>